package main

// CompanyNames maps stock symbols to company names
var CompanyNames = map[string]string{
	// Dow Jones
	"AAPL": "Apple", "AMGN": "Amgen", "AXP": "American Express", "BA": "Boeing",
	"CAT": "Caterpillar", "CRM": "Salesforce", "CSCO": "Cisco", "CVX": "Chevron",
	"DIS": "Disney", "DOW": "Dow Inc", "GS": "Goldman Sachs", "HD": "Home Depot",
	"HON": "Honeywell", "IBM": "IBM", "JNJ": "Johnson & Johnson", "JPM": "JPMorgan Chase",
	"KO": "Coca-Cola", "MCD": "McDonald's", "MMM": "3M", "MRK": "Merck",
	"MSFT": "Microsoft", "NKE": "Nike", "NVDA": "NVIDIA", "PG": "Procter & Gamble",
	"SHW": "Sherwin-Williams", "TRV": "Travelers", "UNH": "UnitedHealth",
	"V": "Visa", "VZ": "Verizon", "WMT": "Walmart",

	// NASDAQ 100
	"ABNB": "Airbnb", "ADBE": "Adobe", "ADI": "Analog Devices",
	"ADP": "ADP", "ADSK": "Autodesk", "AEP": "American Electric Power",
	"AMAT": "Applied Materials", "AMD": "AMD", "AMZN": "Amazon",
	"ANSS": "ANSYS", "APP": "AppLovin", "ARM": "ARM Holdings",
	"ASML": "ASML", "AVGO": "Broadcom", "AZN": "AstraZeneca",
	"BIIB": "Biogen", "BKNG": "Booking Holdings", "BKR": "Baker Hughes",
	"CCEP": "Coca-Cola Europacific", "CDNS": "Cadence Design", "CDW": "CDW",
	"CEG": "Constellation Energy", "CHTR": "Charter Communications", "CMCSA": "Comcast",
	"COST": "Costco", "CPRT": "Copart", "CRWD": "CrowdStrike",
	"CSGP": "CoStar Group", "CSX": "CSX", "CTAS": "Cintas",
	"CTSH": "Cognizant", "DASH": "DoorDash", "DDOG": "Datadog",
	"DLTR": "Dollar Tree", "DXCM": "DexCom", "EA": "Electronic Arts",
	"EXC": "Exelon", "FANG": "Diamondback Energy", "FAST": "Fastenal",
	"FTNT": "Fortinet", "GEHC": "GE HealthCare", "GFS": "GlobalFoundries",
	"GILD": "Gilead Sciences", "GOOG": "Alphabet (C)", "GOOGL": "Alphabet (A)",
	"IDXX": "IDEXX Laboratories", "ILMN": "Illumina", "INTC": "Intel",
	"INTU": "Intuit", "ISRG": "Intuitive Surgical", "KDP": "Keurig Dr Pepper",
	"KHC": "Kraft Heinz", "KLAC": "KLA Corporation", "LIN": "Linde",
	"LRCX": "Lam Research", "LULU": "Lululemon", "MAR": "Marriott",
	"MCHP": "Microchip Technology", "MDB": "MongoDB", "MDLZ": "Mondelez",
	"MELI": "MercadoLibre", "META": "Meta Platforms", "MNST": "Monster Beverage",
	"MRNA": "Moderna", "MRVL": "Marvell Technology", "MU": "Micron",
	"NFLX": "Netflix", "NXPI": "NXP Semiconductors", "ODFL": "Old Dominion Freight",
	"ON": "ON Semiconductor", "ORLY": "O'Reilly Automotive", "PANW": "Palo Alto Networks",
	"PAYX": "Paychex", "PCAR": "PACCAR", "PDD": "PDD Holdings",
	"PEP": "PepsiCo", "PYPL": "PayPal", "QCOM": "Qualcomm",
	"REGN": "Regeneron", "ROP": "Roper Technologies", "ROST": "Ross Stores",
	"SBUX": "Starbucks", "SMCI": "Super Micro Computer", "SNPS": "Synopsys",
	"TEAM": "Atlassian", "TMUS": "T-Mobile", "TSLA": "Tesla",
	"TTD": "The Trade Desk", "TTWO": "Take-Two Interactive", "TXN": "Texas Instruments",
	"VRSK": "Verisk Analytics", "VRTX": "Vertex Pharmaceuticals", "WBD": "Warner Bros Discovery",
	"WDAY": "Workday", "XEL": "Xcel Energy", "ZS": "Zscaler",

	// S&P 500 (beyond Dow and NASDAQ 100)
	"A": "Agilent Technologies", "ABBV": "AbbVie", "ABT": "Abbott", "ACGL": "Arch Capital",
	"ACN": "Accenture", "ADM": "Archer-Daniels-Midland", "AEE": "Ameren",
	"AES": "AES Corporation", "AFL": "Aflac", "AIG": "AIG",
	"AIZ": "Assurant", "AJG": "Arthur J. Gallagher", "AKAM": "Akamai Technologies",
	"ALB": "Albemarle", "ALGN": "Align Technology", "ALL": "Allstate",
	"ALLE": "Allegion", "AMCR": "Amcor", "AME": "AMETEK",
	"AMP": "Ameriprise Financial", "AMT": "American Tower", "ANET": "Arista Networks",
	"AON": "Aon", "AOS": "A.O. Smith", "APA": "APA Corporation",
	"APD": "Air Products", "APH": "Amphenol", "APTV": "Aptiv",
	"ARE": "Alexandria Real Estate", "ATO": "Atmos Energy", "AVB": "AvalonBay Communities",
	"AVY": "Avery Dennison", "AWK": "American Water Works", "AXON": "Axon Enterprise",
	"AZO": "AutoZone",
	"BAC": "Bank of America", "BALL": "Ball Corporation", "BAX": "Baxter International",
	"BBWI": "Bath & Body Works", "BBY": "Best Buy", "BDX": "Becton Dickinson",
	"BEN": "Franklin Templeton", "BF.B": "Brown-Forman", "BG": "Bunge",
	"BIO": "Bio-Rad Laboratories", "BK": "BNY Mellon", "BLK": "BlackRock",
	"BLDR": "Builders FirstSource", "BMY": "Bristol-Myers Squibb",
	"BR": "Broadridge Financial", "BRK.A": "Berkshire (A)", "BRK.B": "Berkshire (B)",
	"BRO": "Brown & Brown", "BSX": "Boston Scientific", "BWA": "BorgWarner",
	"BX": "Blackstone", "BXP": "BXP Inc",
	"C": "Citigroup", "CAG": "Conagra Brands", "CAH": "Cardinal Health",
	"CARR": "Carrier Global", "CB": "Chubb", "CBOE": "Cboe Global Markets",
	"CBRE": "CBRE Group", "CCI": "Crown Castle", "CCL": "Carnival",
	"CE": "Celanese", "CF": "CF Industries", "CFG": "Citizens Financial",
	"CHD": "Church & Dwight", "CHRW": "C.H. Robinson", "CI": "Cigna",
	"CINF": "Cincinnati Financial", "CL": "Colgate-Palmolive", "CLX": "Clorox",
	"CMA": "Comerica", "CME": "CME Group", "CMG": "Chipotle",
	"CMI": "Cummins", "CMS": "CMS Energy", "CNC": "Centene",
	"CNP": "CenterPoint Energy", "COF": "Capital One", "COO": "CooperCompanies",
	"COP": "ConocoPhillips", "COR": "Cencora", "CPAY": "Corpay",
	"CPB": "Campbell Soup", "CPT": "Camden Property Trust", "CRL": "Charles River Labs",
	"CTLT": "Catalent", "CTRA": "Coterra Energy", "CTVA": "Corteva",
	"CVS": "CVS Health",
	"D":   "Dominion Energy", "DAL": "Delta Air Lines", "DAY": "Dayforce",
	"DD": "DuPont", "DE": "Deere & Co", "DECK": "Deckers Outdoor",
	"DELL": "Dell Technologies", "DFS": "Discover Financial", "DG": "Dollar General",
	"DGX": "Quest Diagnostics", "DHI": "D.R. Horton", "DHR": "Danaher",
	"DLR": "Digital Realty", "DOC": "Healthpeak Properties", "DOV": "Dover",
	"DPZ": "Domino's Pizza", "DRI": "Darden Restaurants", "DTE": "DTE Energy",
	"DUK": "Duke Energy", "DVA": "DaVita", "DVN": "Devon Energy",
	"EBAY": "eBay", "ECL": "Ecolab", "ED": "Consolidated Edison",
	"EFX": "Equifax", "EG": "Everest Group", "EIX": "Edison International",
	"EL": "Estee Lauder", "ELV": "Elevance Health", "EMN": "Eastman Chemical",
	"EMR": "Emerson Electric", "ENPH": "Enphase Energy", "EOG": "EOG Resources",
	"EPAM": "EPAM Systems", "EQIX": "Equinix", "EQR": "Equity Residential",
	"EQT": "EQT Corporation", "ERIE": "Erie Indemnity", "ES": "Eversource Energy",
	"ESS": "Essex Property Trust", "ETN": "Eaton", "ETR": "Entergy",
	"EVRG": "Evergy", "EW": "Edwards Lifesciences", "EXPD": "Expeditors International",
	"EXPE": "Expedia", "EXR": "Extra Space Storage",
	"F": "Ford", "FCX": "Freeport-McMoRan", "FDS": "FactSet Research",
	"FDX": "FedEx", "FE": "FirstEnergy", "FFIV": "F5",
	"FI": "Fiserv", "FICO": "Fair Isaac", "FIS": "Fidelity National Info",
	"FITB": "Fifth Third Bancorp", "FMC": "FMC Corporation", "FOX": "Fox Corp (B)",
	"FOXA": "Fox Corp (A)", "FRT": "Federal Realty", "FSLR": "First Solar",
	"FTV": "Fortive",
	"GD":  "General Dynamics", "GDDY": "GoDaddy", "GE": "GE Aerospace",
	"GEN": "Gen Digital", "GEV": "GE Vernova", "GIS": "General Mills",
	"GL": "Globe Life", "GLW": "Corning", "GM": "General Motors",
	"GNRC": "Generac", "GPC": "Genuine Parts", "GPN": "Global Payments",
	"GRMN": "Garmin", "GWW": "W.W. Grainger",
	"HAL": "Halliburton", "HAS": "Hasbro", "HBAN": "Huntington Bancshares",
	"HCA": "HCA Healthcare", "HES": "Hess", "HIG": "Hartford Financial",
	"HII": "Huntington Ingalls", "HLT": "Hilton Worldwide", "HOLX": "Hologic",
	"HPE": "Hewlett Packard Enterprise", "HPQ": "HP Inc", "HRL": "Hormel Foods",
	"HSIC": "Henry Schein", "HST": "Host Hotels", "HSY": "Hershey",
	"HUBB": "Hubbell", "HUM": "Humana", "HWM": "Howmet Aerospace",
	"ICE": "Intercontinental Exchange", "IEX": "IDEX", "IFF": "International Flavors",
	"INCY": "Incyte", "INVH": "Invitation Homes", "IP": "International Paper",
	"IPG": "Interpublic Group", "IQV": "IQVIA", "IR": "Ingersoll Rand",
	"IRM": "Iron Mountain", "IT": "Gartner", "ITW": "Illinois Tool Works",
	"IVZ": "Invesco",
	"J":   "Jacobs Solutions", "JBHT": "J.B. Hunt", "JBL": "Jabil",
	"JCI": "Johnson Controls", "JKHY": "Jack Henry", "JNPR": "Juniper Networks",
	"K": "Kellanova", "KEY": "KeyCorp", "KEYS": "Keysight Technologies",
	"KIM": "Kimco Realty", "KKR": "KKR & Co", "KMB": "Kimberly-Clark",
	"KMI": "Kinder Morgan", "KMX": "CarMax", "KR": "Kroger",
	"L": "Loews", "LDOS": "Leidos", "LEN": "Lennar",
	"LH": "Labcorp", "LHX": "L3Harris Technologies", "LKQ": "LKQ Corporation",
	"LLY": "Eli Lilly", "LMT": "Lockheed Martin", "LNT": "Alliant Energy",
	"LOW": "Lowe's", "LUV": "Southwest Airlines", "LVS": "Las Vegas Sands",
	"LW": "Lamb Weston", "LYB": "LyondellBasell", "LYV": "Live Nation",
	"MA": "Mastercard", "MAA": "Mid-America Apartment", "MAS": "Masco",
	"MCK": "McKesson", "MCO": "Moody's", "MDT": "Medtronic",
	"MET": "MetLife", "MGM": "MGM Resorts", "MHK": "Mohawk Industries",
	"MKC": "McCormick", "MKTX": "MarketAxess", "MLM": "Martin Marietta",
	"MMC": "Marsh & McLennan", "MO": "Altria", "MOH": "Molina Healthcare",
	"MOS": "Mosaic Company", "MPC": "Marathon Petroleum", "MPWR": "Monolithic Power",
	"MRO": "Marathon Oil", "MS": "Morgan Stanley", "MSCI": "MSCI",
	"MSI": "Motorola Solutions", "MTB": "M&T Bank", "MTCH": "Match Group",
	"MTD":  "Mettler-Toledo",
	"NCLH": "Norwegian Cruise Line", "NDAQ": "Nasdaq Inc", "NDSN": "Nordson",
	"NEE": "NextEra Energy", "NEM": "Newmont", "NI": "NiSource",
	"NOC": "Northrop Grumman", "NOW": "ServiceNow", "NRG": "NRG Energy",
	"NSC": "Norfolk Southern", "NTAP": "NetApp", "NTRS": "Northern Trust",
	"NUE": "Nucor", "NVR": "NVR Inc", "NWS": "News Corp (B)",
	"NWSA": "News Corp (A)",
	"O":    "Realty Income", "OKE": "ONEOK", "OMC": "Omnicom",
	"ORCL": "Oracle", "OTIS": "Otis Worldwide", "OXY": "Occidental Petroleum",
	"PARA": "Paramount Global", "PAYC": "Paycom", "PCG": "PG&E",
	"PEG": "Public Service Enterprise", "PFE": "Pfizer", "PFG": "Principal Financial",
	"PGR": "Progressive", "PH": "Parker Hannifin", "PHM": "PulteGroup",
	"PKG": "Packaging Corp", "PLD": "Prologis", "PLTR": "Palantir",
	"PM": "Philip Morris", "PNC": "PNC Financial", "PNR": "Pentair",
	"PNW": "Pinnacle West Capital", "PODD": "Insulet", "POOL": "Pool Corporation",
	"PPG": "PPG Industries", "PPL": "PPL Corporation", "PRU": "Prudential Financial",
	"PSA": "Public Storage", "PSX": "Phillips 66", "PTC": "PTC Inc",
	"PWR":  "Quanta Services",
	"QRVO": "Qorvo",
	"RCL":  "Royal Caribbean", "REG": "Regency Centers", "RF": "Regions Financial",
	"RJF": "Raymond James", "RL": "Ralph Lauren", "RMD": "ResMed",
	"ROK": "Rockwell Automation", "ROL": "Rollins", "RSG": "Republic Services",
	"RTX":  "RTX",
	"SBAC": "SBA Communications", "SCHW": "Charles Schwab", "SJM": "J.M. Smucker",
	"SLB": "Schlumberger", "SNA": "Snap-on", "SO": "Southern Company",
	"SOLV": "Solventum", "SPG": "Simon Property Group", "SPGI": "S&P Global",
	"SRE": "Sempra", "STE": "STERIS", "STLD": "Steel Dynamics",
	"STT": "State Street", "STX": "Seagate Technology", "STZ": "Constellation Brands",
	"SWK": "Stanley Black & Decker", "SWKS": "Skyworks Solutions", "SYF": "Synchrony Financial",
	"SYK": "Stryker", "SYY": "Sysco",
	"T": "AT&T", "TAP": "Molson Coors", "TDG": "TransDigm",
	"TDY": "Teledyne Technologies", "TECH": "Bio-Techne", "TEL": "TE Connectivity",
	"TER": "Teradyne", "TFC": "Truist", "TFX": "Teleflex",
	"TGT": "Target", "TJX": "TJX Companies", "TMO": "Thermo Fisher",
	"TPR": "Tapestry", "TRGP": "Targa Resources", "TRMB": "Trimble",
	"TROW": "T. Rowe Price", "TSCO": "Tractor Supply", "TSN": "Tyson Foods",
	"TT": "Trane Technologies", "TXT": "Textron", "TYL": "Tyler Technologies",
	"UAL": "United Airlines", "UBER": "Uber Technologies", "UDR": "UDR Inc",
	"UHS": "Universal Health Services", "ULTA": "Ulta Beauty", "UNP": "Union Pacific",
	"UPS": "UPS", "URI": "United Rentals", "USB": "US Bancorp",
	"VICI": "VICI Properties", "VLO": "Valero Energy", "VLTO": "Veralto",
	"VMC": "Vulcan Materials", "VRSN": "VeriSign", "VST": "Vistra",
	"VTR": "Ventas", "VTRS": "Viatris",
	"WAB": "Westinghouse Air Brake", "WAT": "Waters Corporation", "WBA": "Walgreens",
	"WDC": "Western Digital", "WEC": "WEC Energy", "WELL": "Welltower",
	"WFC": "Wells Fargo", "WM": "Waste Management", "WMB": "Williams Companies",
	"WRB": "Berkley Corporation", "WST": "West Pharmaceutical", "WTW": "Willis Towers Watson",
	"WY": "Weyerhaeuser", "WYNN": "Wynn Resorts",
	"XOM": "Exxon Mobil", "XYL": "Xylem",
	"YUM": "Yum! Brands",
	"ZBH": "Zimmer Biomet", "ZBRA": "Zebra Technologies", "ZTS": "Zoetis",

	// Hang Seng (Hong Kong)
	"0001.HK": "CK Hutchison", "0002.HK": "CLP Holdings", "0003.HK": "HK & China Gas",
	"0005.HK": "HSBC Holdings", "0006.HK": "Power Assets", "0011.HK": "Hang Seng Bank",
	"0012.HK": "Henderson Land", "0016.HK": "SHK Properties", "0017.HK": "New World Dev",
	"0019.HK": "Swire Pacific A", "0027.HK": "Galaxy Entertainment", "0066.HK": "MTR Corporation",
	"0083.HK": "Sino Land", "0101.HK": "Hang Lung Properties", "0175.HK": "Geely Automobile",
	"0241.HK": "Alibaba Health", "0267.HK": "CITIC", "0288.HK": "WH Group",
	"0291.HK": "China Resources Beer", "0316.HK": "Orient Overseas", "0386.HK": "China Petroleum",
	"0388.HK": "HK Exchanges", "0669.HK": "Techtronic", "0688.HK": "China Overseas",
	"0700.HK": "Tencent", "0762.HK": "China Unicom", "0823.HK": "Link REIT",
	"0857.HK": "PetroChina", "0868.HK": "Xinyi Glass", "0881.HK": "Zhongsheng Group",
	"0883.HK": "CNOOC", "0939.HK": "CCB", "0941.HK": "China Mobile",
	"0960.HK": "Longfor Group", "0968.HK": "Xinyi Solar", "0981.HK": "SMIC",
	"0992.HK": "Lenovo Group", "1038.HK": "CK Infrastructure", "1044.HK": "Hengan International",
	"1093.HK": "CSPC Pharmaceutical", "1109.HK": "China Resources Land", "1113.HK": "CK Asset",
	"1177.HK": "Sino Biopharm", "1209.HK": "China Resources Mix", "1211.HK": "BYD",
	"1299.HK": "AIA Group", "1378.HK": "China Hongqiao", "1398.HK": "ICBC",
	"1810.HK": "Xiaomi", "1876.HK": "Budweiser APAC", "1928.HK": "Sands China",
	"1997.HK": "Wharf REIC", "2007.HK": "Country Garden", "2018.HK": "AAC Technologies",
	"2020.HK": "ANTA Sports", "2269.HK": "WuXi Biologics", "2313.HK": "Shenzhou International",
	"2318.HK": "Ping An Insurance", "2319.HK": "Mengniu Dairy", "2331.HK": "Li Ning",
	"2382.HK": "Sunny Optical", "2388.HK": "BOC Hong Kong", "2628.HK": "China Life",
	"2688.HK": "ENN Energy", "3328.HK": "Bank of Communications", "3690.HK": "Meituan",
	"3968.HK": "China Merchants Bank", "3988.HK": "Bank of China", "6098.HK": "Country Garden Services",
	"6862.HK": "Haidilao", "9618.HK": "JD.com", "9633.HK": "Nongfu Spring",
	"9888.HK": "Baidu", "9961.HK": "Trip.com", "9988.HK": "Alibaba",
	"0268.HK": "Kingdee International", "0285.HK": "BYD Electronic",
	"0772.HK": "China Literature", "1024.HK": "Kuaishou Technology",
	"1088.HK": "China Shenhua Energy", "1347.HK": "Hua Hong Semiconductor",
	"1833.HK": "Ping An Healthcare", "1972.HK": "Swire Properties",
	"2015.HK": "Li Auto", "2057.HK": "ZTO Express",
	"3692.HK": "Hansoh Pharmaceutical", "6060.HK": "ZhongAn Online P&C Insurance",
	"6160.HK": "BeiGene", "6618.HK": "JD Health International",
	"9626.HK": "Bilibili", "9698.HK": "GreenTown Service",
	"9866.HK": "NIO", "9868.HK": "XPeng",
	"9901.HK": "New Oriental Education", "9999.HK": "NetEase",
}

// GetCompanyName returns the company name for a symbol
func GetCompanyName(symbol string) string {
	if name, ok := CompanyNames[symbol]; ok {
		return name
	}
	return ""
}

// GetCompanyNamesForSymbols returns a map of company names for a list of symbols
func GetCompanyNamesForSymbols(symbols []string) map[string]string {
	result := make(map[string]string)
	for _, sym := range symbols {
		if name := GetCompanyName(sym); name != "" {
			result[sym] = name
		}
	}
	return result
}
